# Generated by Django 3.2 on 2021-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('purchase_link', models.CharField(default='http://www.amazon.com', max_length=450)),
            ],
        ),
    ]
