# Generated by Django 3.2 on 2021-05-29 00:00

import book_reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.JSONField(default=book_reviews.models.my_default),
        ),
    ]
